### ISSUE TITLE
Credentials caching

### ISSUE THREAD

**Issue by jogold** [CoffeeAndCode/aws-auth-helper#19]
Hi @jonknapp,

Any plans to add credentials caching?

**Comment by jonknapp** [comment]
Not personally, but I can take a look at a PR for this. I use mostly one operating system so I'm not sure of the impact anywhere else.

This was brought up before in https://github.com/CoffeeAndCode/aws-auth-helper/issues/2

Since the env output can be exported to the shell I didn't think caching was needed. It doesn't help across terminal windows though.

**Comment by jogold** [comment]
Hi @jonknapp,

The solution proposed in #2 looks fine to me. Thanks for the quick reply and this package!

**Comment by jonknapp** [comment]
Thanks for saying thanks! Have a good one!
